from app.workflow import process_get_answer

async def get_rag_answer(question: str) -> str:
    """
    Process a question using the RAG system and return the answer.
    
    Args:
        question (str): The question to be answered
        
    Returns:
        str: The answer generated by the RAG system
    """
    try:
        answer = await process_get_answer(question)
        return answer
    except Exception as e:
        raise Exception(f"Error processing question: {str(e)}")
