from app.workflow import process_get_answer
import re
import logging

# Configure logger
logging.basicConfig(level=logging.INFO)

def clean_text(text: str) -> str:
    """
    Clean the text while preserving markdown formatting.
    
    Args:
        text (str): The text to clean
        
    Returns:
        str: The cleaned text with preserved markdown
    """
    # Remove any extra whitespace between sections while preserving markdown
    text = re.sub(r'\n{3,}', '\n\n', text)
    
    # Ensure proper spacing for headers
    text = re.sub(r'(?m)^(#{1,6})(?!#)\s*(.+?)$', r'\n\1 \2\n', text)
    
    # Clean up bullet points
    text = re.sub(r'(?m)^\s*[-*]\s+', '* ', text)
    
    # Ensure proper spacing for lists
    text = re.sub(r'\n{2,}(?=[-*])', '\n', text)
    
    # Remove any trailing whitespace
    text = text.strip()
    
    return text

async def get_rag_answer(question: str) -> str:
    """
    Process a question using the RAG system and return the answer.
    
    Args:
        question (str): The question to be answered
        
    Returns:
        str: The answer generated by the RAG system
    """
    logging.info("Starting to process the question using RAG system.")
    try:
        answer = await process_get_answer(question)
        logging.info("Successfully processed the question using RAG system.")
        return clean_text(answer)
    except Exception as e:
        logging.error(f"Error processing question: {str(e)}")
        raise Exception(f"Error processing question: {str(e)}")
